#name: Interval
#
#on:
#  workflow_dispatch:
#  pull_request:
#    branches:
#      - main
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    name: 'Run tests'
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pages: write
#
#    services:
#      selenium:
#        image: selenium/standalone-chrome:latest
#        options: --shm-size 2g
#        ports:
#          - 4444:4444
#
#    steps:
#      - name: Git clone
#        uses: actions/checkout@v4
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'corretto'
#          cache: 'maven'
#
#      - name: Create demo.properties file
#        run: |
#          mkdir -p src/test/resources
#          cat > src/test/resources/demo.properties << EOF
#          baseUrl=${{ secrets.BASE_URL }}
#          userName=${{ secrets.USER_NAME }}
#          password=${{ secrets.PASSWORD }}
#          EOF
#
#      - name: Maven test
#        env:
#          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
#        run: mvn clean test -Denv=demo -Dsuite=interval
#
#      - name: Get Allure history
#        uses: actions/checkout@v4
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Build Allure report
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: target/allure-results
#          gh_pages: gh-pages
#          allure_report: allure-report
#          allure_history: allure-history
#          keep_reports: 100
#
#      - name: Publish Allure report to Github Pages
#        if: ${{ success() || failure() }}
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
